version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/mmbabu1988/Sample_scripted-pipeline-project/environment-variables
          username: $mmbabu88
          password: $Mahesh@123
jobs:
  my-job-name:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # echo Hello, World!

workflows:
  my-custom-workflow:
    jobs:
      - my-job-name